import { NextResponse } from 'next/server';
import { LegalAdvisor } from '@/lib/rag-store';

export async function POST(req: Request) {
  try {
    const { query } = await req.json();
    
    if (!query) {
      return NextResponse.json({ error: 'Query is required' }, { status: 400 });
    }

    const advisor = new LegalAdvisor();
    const report = await advisor.queryLegalContext(query);

    return NextResponse.json({ report: report, context: "Generated by LegalAdvisor AI based on actual Indian legal context." });
  } catch (error) {
    console.error('Error in Legal RAG route:', error);
    return NextResponse.json({ error: 'Failed to generate legal report' }, { status: 500 });
  }
}
